
name: CI

on: 
  push:
    branches:
      - main

jobs:
  build:

    runs-on: macOS-latest
    strategy: 
      matrix:
        run-config:
          - { scheme: 'MacPlatformTest', destination: 'platform=macOS'}
    
    steps:
    - name: Checkout Project
      uses: actions/checkout@v1

    - name: List Available Applications
      run: ls /Applications

    - name: Switch to Xcode 13
      run: sudo xcode-select -s /Applications/Xcode_13.2.1.app

    - name: Show Build Version
      run: xcodebuild -version

    - name: Show Build Settings
      run: xcodebuild -showBuildSettings
      
    - name: Show Build SDK
      run: xcodebuild -showsdks
    
    - name: Show Available Destinations
      env:
        scheme: ${{ matrix.run-config['scheme'] }}    
      run: xcodebuild -scheme ${scheme} -showdestinations
    
    - name: Run Build
      env:
          SCHEME: ${{ matrix.run-config['scheme'] }}
          DESTINATION: ${{ matrix.run-config['destination'] }}

      run: ./ci-build.sh

    - name: Print HW Model
      run: sysctl hw.model

    - name: Run CPU sysctl
      run: sysctl -a | grep cpu

    - name: Run Binary
      run: ./ci-run.sh
